let clanky = [
    { "title": "Kupadelné svátky", "content": "<p>Kupadelné svátky je označení pro slovanské oslavy letního slunovratu. Byly vázány na církevní svátek Jana Křtitele (rusky Иван Купала – Ivan Kupala), tj. na svatojánskou noc z 23. na 24. června nebo na období mezi tímto večerem a svátkem sv. Petra 29. června. Tomuto období předchází v pravoslavném prostředí letnice, během nichž se také dodržovaly další příbuzné zvyky mezi něž patří rusalné svátky. Původ svátků a zvyků ovšem leží v období před christianizací.</p><p>Smyslem svátku bylo zajištění zdárné úrody a to skrze vláhu přivolanou koupelemi, teplo přivolané ohni a plodnost přivolanou skrze sexuální nevázanost. V kupadelných písních se objevuje motiv sňatku bratra a sestry – ohně a vody, dvou hlavních živlů tohoto svátku. Jeho symbolickým vyjádřením je modrožlutý květ černýše hajního. Tento motiv se objevuje i v jiných indoevropských mytologiích.</p><p>Dále byly pleteny věnce a mládež se jimi zdobila. Ty byly také, často doplněné svícemi, dívkami posílány po vodě a ty z jejich pohybu věštily své štěstí ve vztazích. Mladí muži se někdy snažili je zachytit aby na sebe upoutali pozornost dívky. Ohně mladíci a dívky přeskakovali nazí, v některých ruských oblastech až do 19. století, a stejně jako koupele to mělo zajistit rituální čistotu a zdraví.</p><p>Stejně jako při mnohých jiných slovanských svátcích letního slunovratu byly dočasně odvrženy normy věrnosti a cudnosti, proti čemuž horlily církevní autority až do novověku. Typickým pokrmem při této slavnosti je pražmo, hledal se bájný kapradinový květ.</p>" },
    { "title": "Datová struktura", "content": "<p>V matematické informatice a programování představuje datová struktura konkrétní způsob organizace dat v paměti počítače, který zajišťuje, aby mohla data být používána efektivně. Datová struktura umožňuje uchovávat a zpracovávat množinu dat stejného typu nebo různorodých, ale logicky souvisejících dat.</p><p>Termín datová struktura může mít několik příbuzných významů:</p><ul><li>abstraktní datový typ,</li><li>implementace abstraktního datového typu,</li><li>instance datového typu, například konkrétní seznam.</li></ul>" },
    { "title": "Bella ciao", "content": "<p>Italská lidová píseň italských partyzánů</p><p>Una mattina mi sono svegliato,<br>o bella, ciao! bella, ciao! bella, ciao, ciao, ciao!<br>Una mattina mi sono svegliato,<br>e ho trovato l'invasor.</p><p>O partigiano, portami via,<br>o bella, ciao! bella, ciao! bella, ciao, ciao, ciao!<br>O partigiano, portami via,<br>ché mi sento di morir.</p><p>E se io muoio da partigiano,<br>o bella, ciao! bella, ciao! bella, ciao, ciao, ciao!<br>E se io muoio da partigiano,<br>tu mi devi seppellir.</p><p>E seppellire lassù in montagna,<br>o bella, ciao! bella, ciao! bella, ciao, ciao, ciao!<br>E seppellire lassù in montagna,<br>sotto l'ombra di un bel fior.</p><p>Tutte le genti che passeranno,<br>o bella, ciao! bella, ciao! bella, ciao, ciao, ciao!<br>Tutte le genti che passeranno,<br>Mi diranno «Che bel fior!»</p><p>«È questo il fiore del partigiano»,<br>o bella, ciao! bella, ciao! bella, ciao, ciao, ciao!<br>«È questo il fiore del partigiano,<br>morto per la libertà!»</p>" },
    { "title": "Ivan Stěpanovič Koněv", "content": "<p>Ivan Stěpanovič Koněv (rusky Иван Степанович Конев; 28. prosince 1897 – 21. května 1973) byl sovětský vojevůdce, maršál Sovětského svazu, hrdina SSSR a hrdina ČSSR. V průběhu druhé světové války velel vojskům Rudé armády na východní frontě, která osvobodila od okupace německými nacisty velkou část východní Evropy. Také se podílel na karpatsko-dukelské operaci v roce 1944, na osvobození německého koncentračního tábora Osvětim. Měl významný podíl na obchvatné viselsko-oderské operaci, kde padlo na 295 000 německých vojáků a dalších 175 000 jich bylo zajato za proporčně mnohem menších sovětských ztrát.</p>" },
    { "title": "Stavové kódy HTTP", "content": "<p>Stavový kód HTTP je součást hlavičky odpovědi serveru na klientský požadavek. Stavový kód upřesňuje, jak byla odpověď serverem zpracována - jestli byl požadavek vyřízen kladně, záporně, nebo došlo k chybě. Dále je na klientovi, aby stavový kód odpovědi interpretoval a následně podnikl patřičné kroky.</p><p>Součástí hlavičky odpovědi spolu se stavovým kódem je také stavové hlášení, což je anglický slovní popis stavového kódu. Jsou rozděleny podle charakteru odpovědi do pěti kategorií - informační, úspěch, přesměrování, chybný požadavek (chyba klienta) a chyba serveru.</p><p>Stavový kód je trojice dekadických čísel, kde první číslo určuje kategorii odpovědi a ostatní čísla jí blíže specifikují.</p><p>Oficiální seznam stavových kódů protokolu HTTP spravuje organizace Internet Assigned Numbers Authority IANA.</p>" },
    { "title": "Das Lied der Deutschen", "content": "<p>Píseň Das Lied der Deutschen (česky Píseň Němců) je německá hymna.</p><p>Její text napsal v roce 1841 německý básník, jazykovědec a historik literatury August Heinrich Hoffmann von Fallersleben. Tato píseň se skládala ze tří slok, z nichž první začínala slovy „Deutschland, Deutschland über alles“. V roce 1922 ji za hymnu oficiálně uznal první prezident Německé republiky, Friedrich Ebert. Zeměpisné údaje, uvedené v první sloce, vymezovaly hranice rozšíření německy mluvícího obyvatelstva v polovině 19. století, a proto po druhé světové válce Spojenci zakázali publikovat a uvádět tuto sloku, jelikož si Německo nemohlo nárokovat území pod kontrolou vítězných mocností. Pokus přijmout novou hymnu v roce 1950 skončil fiaskem. V roce 1952 byla jako hymna tehdejšího Západního Německa přijata třetí sloka „Einigkeit und Recht und Freiheit“ (Jednota, právo a svoboda). Zůstala jako hymna i po sjednocení, čímž v tomto kontextu nabyla dalšího významu.</p>" },
    { "title": "Dáda Patrasová", "content": "<p>Dáda Patrasová Slovačisková zahájila svoji uměleckou kariéru v roce 1884 jako krasojezdkyně cirkusu Kludský (viz Josef Lada-Kocour Mikeš). Od počátku 20. století se pak pod uměleckým jménem Ljuba Hermanová věnovala filmu, kabaretu a s příchodem televize zpěvu pražských popěvků. Televize otevřela Dádě zcela nové a netušené obzory. V letech 1983 - 2003 natáčela pro Československou televizi první pornoseriál Návštěvníci (viz obrázek). Erotické tématice se na obrazovce věnovala i v pravidelných pořadech pro děti, které byly velmi oblíbené mezi pedofily. Dnes si Dáda nechala implantovat blond vlasy a černé brýle a stala se sexuálním idolem pubertální mládeže jako Toxic Babe Dáda Patrasová.</p>" },
    { "title": "Uhersko", "content": "<p>Uhersko či Uhry (maďarsky Magyarország, německy Ungarn, latinsky Hungaria), oficiálním názvem Uherské království (maďarsky Magyar Királyság [maďar kirájšág]; latinsky Regnum Hungariae), byl historický mnohonárodnostní státní útvar s maďarskou hegemonií, rozkládající se od 10. století do roku 1918 na pomezí střední a jihovýchodní Evropy, konkrétně na území dnešního Maďarska a Slovenska a dále v částech dnešního Rumunska (Banát, Sedmihradsko), Rakouska (Burgenland a malé části Dolních Rakous), Polska (malé části Spiše a Oravy – dnes v Malopolském vojvodství), Ukrajiny (Podkarpatská Rus), Srbska (Banát a Bačka – dnes ve Vojvodině), Chorvatska (Baranja, Mezimuří) a Slovinska (Zámuří).</p><p>Hranice Uherska byly prakticky v celé délce přirozeně determinované: na severu, východě a jihovýchodě se jednalo o hlavní oblouk Karpat, na jihu velké řeky (Dunaj, Dráva, případně Sáva), na západě východní úbočí Alp, na severozápadě řeka Morava. Rozsah státu je tak dobře patrný i na čistě fyzické mapě.</p>" },
    { "title": "Škola čar a kouzel v Bradavicích", "content": "<p>Škola čar a kouzel v Bradavicích, zkráceně Bradavice (anglicky Hogwarts School of Witchcraft and Wizardry, zkráceně Hogwarts) je kouzelnická škola v příbězích o Harrym Potterovi.</p><p>Škola byla před více než tisíci lety založena čtyřmi největšími čarodějkami a čaroději té doby – Godrikem Nebelvírem, Helgou z Mrzimoru, Rowenou z Havraspáru a Salazarem Zmijozelem. Podle nich byly pojmenovány čtyři koleje – Nebelvír, Mrzimor, Havraspár a Zmijozel. Heslem školy je Draco dormiens nunquam titillandus – „Nikdy nelechtej spícího draka“. Existuje také hymna Bradavic. Škola je rozlehlá, stojí na skále nad jezerem někde ve Skotské vysočině. Mudlům se díky kouzlu jeví jako zřícenina a bojí se tam chodit. Studenti se do školy dostanou vlakem, který odjede 1. září z londýnského nádraží King's Cross vždy v jedenáct hodin z nástupiště 9 a 3/4.</p>" },
    { "title": "Buddhismus", "content": "<p>Buddhismus dnešní dobou označuje širokou rodinu filozofických a náboženských škol, původem z indického subkontinentu, založených na učení Siddhártha Gautamy, běžně známého jako Buddha, což znamená „probuzený“. Buddha žil a učil na území dnešní severovýchodní Indie někdy mezi 6. a 4. stoletím př. n. l. Buddhisté jej respektují jako svého probuzeného či osvíceného učitele.</p><p>Ačkoliv buddhismus zůstává stále nejrozšířenější v Asii, jeho jednotlivé školy můžete dnes nalézt na celém světě. Odhady se pohybují mezi 350 milióny až 1,5 miliardou lidí, kde dnes nejčastěji akceptovaným rozpětím je 350 - 550 milionů. V současné Indii buddhismus dnes téměř vymizel.</p><p>Buddhismus bývá někdy mylně označován jako neteistické náboženství především proto, že se v buddhistických textech objevují „božstva“ jakožto třída bytostí, žijící v jiných dimenzích. Na rozdíl od teistických náboženství jsou však tyto bytosti z třídy božstev považována za smrtelné a nevědomé bytosti podobně jako bytosti z třídy lidí nebo zvířat, pouze je převyšují svými schopnostmi a dlouhověkostí.</p><p>Z období Buddhova života o něm neexistují žádné písemné zprávy, naše znalosti jeho učení vychází z tzv. Tipitaky, která sice byla sepsána až po jeho smrti, nicméně se lze domnívat, že v ní je obsaženo učení velmi blízké původnímu učení Buddhy.</p>" },
    { "title": "Sex na vesnici", "content": "<p>Na vesnici je sex velice oblíbená činnost, protože zemědělce nic neuspokojí tak, jako když může pořádně rozrýt brázdu a sázet do ní okurek (v Čechách okurku). Při svých praktikách často rádi používají pomůcky, například opratě, násady od vidlí (sadomasochisti je používají obráceně) nebo cepy (odtud pochází rčení, že je dívka řádně vycepovaná).</p><p>Venkov zdá se přeje úchylkám všeho druhu - ve velkém měřítku zde bují například zoofilie, dokonce jsou zakládána jednotná zoofilní družstva (JZD), která mezi sebou soutěží třeba v tahání krav za struky a jejich následné inseminaci. Nejoblíbenější je prý poloha „na koně“.</p>" },
    { "title": "Šachbox", "content": "<p>Šachbox (z anglického Chess boxing) je sportovní odvětví kombinující box a šachy. Soupeři se střetávají v utkání, ve kterém se střídají šachová kola s koly boxovými. Každé kolo trvá 3 minuty. Hraje se 11 kol - 6 šachových a 5 boxových. První zápasy zorganizoval Nizozemec Iepe Rubingh, který se sám inspiroval ve scifi komiksu Chladný rovník Enkiho Bilala z roku 1992.</p><p>Utkání trvá jedenáct kol, první a poslední kolo je šachové. Mezi jednotlivými koly jsou minutové přestávky. Šachová kola tvoří partii v rapid šachu, na kterou má každý ze soupeřů dvanáct minut. Utkání může skončit knockoutem, rozhodnutím rozhodčího, matem, po vypršení časového limitu šachové partie, nebo vzdáním se soupeře.</p>" },
    { "title": "Suši", "content": "<p>Suši (sushi, japonsky 寿司) je jedno z nejznámějších jídel japonské kuchyně. Většina lidí si pod tímto pojmem představí zejména syrové rybí maso s rýží, ale suši je především vařená rýže spojená se speciální sladkokyselou omáčkou sušinoko připravenou k tomuto účelu. Také slovo suši v doslovném překladu z japonštiny znamená „kyselá chuť“.</p>" },
    { "title": "Mužský pohlavní orgán", "content": "<p>Pohlavní orgán obecně je příslušník dopravní policie pohybující se po hlavní komunikaci, sledující pohlavní pohyb a číhající na vhodnou oběť. Pohlavní orgán se dělí na mužský a ženský, tato odborná stať se však bude zabývat pouze mužským pohlavním orgánem, protože způsobuje větší problémy. Protože se pokládá za neslušné, aby se mužský pohlavní orgán ukazoval na veřejnosti, tak se většinou ukrývá. Obvykle někde za stromem nebo křovím, někdy za rohem budovy, někdy v autě a někdy se dokonce i maskuje. Přesto lze z různých očitých svědectví nebohých účastníků pohlavního pohybu, které mužský pohlavní orgán ulovil, poměrně přesně jeho vzhled a chování popsat.</p><h3>Rozměry mužského pohlavního orgánu</h3><p>Není pravda, když se občas říká, že na rozměrech mužského pohlavního orgánu nezáleží. Záleží na nich docela dost, a to na tloušťce i na délce. Malý a hubený mužský pohlavní orgán nevzbuzuje náležitý respekt, proto je lepší, když je spíše dlouhý a přijatelně tlustý. Přesné rozměry je zbytečné uvádět, neboť každý má o tloušťce a délce mužského pohlavního orgánu trochu jiné představy, je to tedy individuální záležitost. V každém případě by ale měl být dlouhý nejméně 18 dm a průměr ve středu alespoň 3 dm – to je minimální hranice pro jeho uspokojivou činnost.</p>" },
    { "title": "Kulturní a sociální antropologie", "content": "<p>Kulturní a sociální antropologie je společenská věda, která se zabývá lidskými kulturami, jejich vznikem a vývojem, srovnáváním různých kultur a významem kultury pro člověka. Na rozdíl od sociologie však vychází od jednotlivce a klade důraz na to, jak lidé svým kulturám a společnostem sami rozumějí. Proto se zajímá také o historii a místní tradice.</p><p>Standardní učebnice kulturní a sociální antropologie zpravidla zahrnují tato hlavní témata:</p><ul><li>člověk a společnost, kultura a socializace;</li><li>společenské systémy, status a role;</li><li>rodina a příbuzenství, příbuzenské systémy;</li><li>prostředí a hospodaření, ekonomie a směna;</li><li>jazyk a společnost, sociolingvistika;</li><li>společenský řád a autorita, moc ve společnosti;</li><li>svátky, rituály a náboženství.</li></ul>" },
    { "title": "Doprava", "content": "<p>Doprava je účelný a zamýšlený pohyb dopravních prostředků po dopravních cestách. Produktem dopravy je přeprava. Dopravní technologie sestávají z dopravních prostředků, dopravní infrastruktury a organizace dopravy.</p><p>Doprava informací se obvykle zařazuje jako samostatný obor, komunikace a telekomunikace. Obojí ovšem úzce souvisí – řízení dopravy nákladu a osob obvykle vyžaduje i spolehlivý přenos informací, jímž se ve vztahu k dopravě zabývá dopravní telematika. Druhem dopravy je také přenos elektrické energie. Tento článek se dále zabývá především dopravou předmětů a osob.</p>" },
    { "title": "Bit za sekundu", "content": "<p>Bit za sekundu (značka bit/s, někdy také b/s, nebo bps z anglického bit per second) je jednotka přenosové rychlosti. Jednotka udává, kolik bitů informace je přeneseno za jednu sekundu.</p>" },
    { "title": "Brno", "content": "<p>Brno (hantec: Štatl, anglicky: Chicago, popřípadě Brünn, rusky: Шалинград, německy Reichsstadtl (viz hantec)), jidiš: ברין; je hlavní vesnicí Moravistánu. Má okolo 10 000 obyvatel, rychle se ale rozrůstá a pro rok 2084 se očekává, že bude mít již 10 003 obyvatel.</p><p>Brno se nachází ve východní části regionu, poblíž sunitsko-křesťanské hranice (Brno stále náleží Sunnitům) a je proslulé svou orientální kulturou. Hlavní pamětihodností je hrad Špilas, jeden z hradů tyčících se nad chatrčemi chudého Moravistánu. Byl postaven v dobách Ottomanské říše, když se Islám rozšířil v Moravistánu (do té doby známého jako Velká Morava).</p>" },
    { "title": "Vyšetřování ztráty třídní knihy", "content": "<p>Vyšetřování ztráty třídní knihy je druhá z nejstarších her v repertoáru Divadla Járy Cimrmana. Autorem hry je Ladislav Smoljak, jako spoluautor je uváděn rovněž fiktivní velký český vynálezce, filosof a dramatik Jára Cimrman. Hra měla premiéru 8. listopadu 1967 v Malostranské besedě v Praze. Do roku 1986 se uskutečnilo celkem 498 repríz.</p>" },
    { "title": "Svobodný software", "content": "<p>Svobodný software, někdy nazývaný free software (z anglického freedom - svoboda) nebo software libre je software, který uživatelé mohou používat k libovolnému účelu, kopírovat, distribuovat, studovat a měnit. Svobodný software je tedy otázka volnosti, nikoliv ceny. Jednotliví uživatelé mohou samostatně nebo společně užívat software jak uznají za vhodné, mohou jej bezplatné či za úplatu distribuovat, nabízet technickou podporu či záruku jako dodatečnou placenou službu. Často tyto služby nabízí přímo autor svobodného softwaru. U svobodného softwaru využívaného k vysoce komerčním účelům (např. Red Hat Enterprise Linux) je placení služeb obvyklé. Mezi nejznámější svobodný software patří například operační systém Linux, prostředí KDE, prostředí GNOME, aplikace na úpravu grafiky GIMP, webový prohlížeč Firefox a kancelářský balík LibreOffice. Množství svobodného softwaru je obrovské a lze nalézt software téměř pro každou oblast použití.</p>" },
    { "title": "Koronavirus", "content": "<p>Jedná se zde o komplexní fenomen, zahrnující nadějně se rozvíjející se epidemii COVID-19 způsobenou koronavirem SARS-CoV-2, spolu s mediálně výživnou paniku, která úspěšně provětrá staré skladové zásoby neprodejných ležáků. Taky je to jedinečná příležitost pro dutoprázdné politiky lacině se prsit před mediálně předzpracovanou veřejností. Podle důvěryhodných konspiračních teorií koronavirus vznikl potměšilou mutací, spojením lidu veleprospěšného čínského jüanu s jadranským mořským ježkem. Jsou obavy, že SARS-CoV-2 je jen další mutací viru, který ve dvacátém století vyvolal pandemii onemocnění, známého coby Dýmějový humor. Což je těžké infekční onemocnění, způsobené RNA viry z čeledi Humoroviridae, které napadá lidi, opice (chechtavka) a prasata (chrochtavka). Některé z kmenů tohoto viru vyvolávaly (a stále vyvolávají) jednu z nejnebezpečnějších nákaz, s jakou se kdy lidstvo setkalo.</p><p>Nový koronavirus rozhodně není z Marsu. Není to ani biologická zbraň. Objevil se v Číně, kde si ho vypěstovala Mrcha Matka Příroda, která si s viry hraje velmi ráda. Naše chyba, že jí málo koukáme do karet. Jestli ale něco fakt může za tuhle pandemii, tak je to tajnůstkářství a papalášství jednoho režimu, který by měl sakra zpytovat svědomí.</p>" },
    { "title": "Paníčitelka", "content": "<p>Paníničitelka (zkráceně pajčitelka (slovensky fajčitelka), pančelka, též <span title=\"píči\" style=\"color:#666666;background-color:white;padding:1px\"><span style=\"visibility: hidden;\">kundice</span></span>telka) je dle psychiatrických standardů klasická diagnóza neuspokojené, životem zklamané ženy s napoleonským syndromem. Dřívější označení soužkačitelka (zkráceně též soudržka, v 5.p souško, v muž.r. souhu) zmizelo společně s nápojem cikorka, mončičáky a céčky.</p><p>Paníčitelky (anglicky Bitchers, polsky Baby Pzrebyteczne, kterýžto výraz bývá ovšem v polštině používán i pro tchýně) slouží k potlačování přirozeného intelektu dětí a jeho nahrazováním těmi správnými politickými názory. K tomu dochází ve státních i soukromých ústavech a specifických věznicích, pro které sice existuje souhrnný název začínající na š, ale v zájmu vašeho psychického a mého fyzického zdraví ho nebudu vyslovovat. Každé takové zařízení je vybaveno sborovnou, kde se každých 45 minut shlukují k tajným konspiračním schůzkám a probírají světonázorové otázky.</p><p>Ve slangu mladé části lidské populace je paníčitelka někdy nazývána též trefnými označeními jako <span title=\"kundice\" style=\"color:#666666;background-color:black;padding:1px\"><span style=\"visibility: hidden;\">kundice</span></span>, <span title=\"čůza\" style=\"color:#666666;background-color:black;padding:1px\"><span style=\"visibility: hidden;\">čůza</span></span>, <span title=\"kočička\" style=\"color:#666666;background-color:black;padding:1px\"><span style=\"visibility: hidden;\">kočička</span></span>, <span title=\"rebeka\" style=\"color:#666666;background-color:black;padding:1px\"><span style=\"visibility: hidden;\">rebeka</span></span>, nebo <span title=\"péro\" style=\"color:#666666;background-color:black;padding:1px\"><span style=\"visibility: hidden;\">péro</span></span>.</p>" },
    { "title": "Queen", "content": "<p>Queen je britská rocková hudební skupina, založená roku 1971 v Londýně. V její původní sestavě byli Freddie Mercury (zpěv, klavír), Brian May (kytara, zpěv), John Deacon (baskytara, klávesy) a Roger Taylor (bicí, zpěv). Prvotní tvorbu skupiny ovlivnil hlavně progresivní rock a hard rock. Postupně se kapela pokoušela o konvenčnější a komerčnější tvorbu, v její tvorbě se tak objevily žánry jako klasický rock, arena rock, pop rock, funk či R&B.</p><p>Před založením skupiny Queen, hráli mezi lety 1968−1970 Brian May a Roger Taylor společně s baskytaristou a zpěvákem Timem Staffellem ve skupině Smile. Freddie Mercury, tehdy ještě známý pod svým rodným jménem Farrokh Bulsara, byl fanouškem této kapely a po Staffellově odchodu v roce 1970 se k nim připojil jako zpěvák. O rok později, v roce 1971, usedl na post baskytaristy John Deacon a skupina se na Mercuryho návrh přejmenovala na Queen.</p>" },
    { "title": "Slivoň", "content": "<p>Slivoň (Prunus) je rozsáhlý rod stromů a keřů z čeledi růžovitých se značným hospodářským a kulturním významem. Zahrnuje velké množství oblíbených ovocných dřevin, jako jsou švestka, meruňka, višeň, třešeň, mandloň a broskvoň, stejně jako druhy planě rostoucí, jako jsou střemcha, trnka či mahalebka. Slivoně se vyznačují jednoduchými, střídavými listy a oboupohlavními, zpravidla vonnými květy. Obsahují množství různých chemických látek, např. toxického amygdalinu. Plodem je peckovice.</p>" },
    { "title": "Dětská práce", "content": "<p>Dětská práce je velmi efektivní forma vykořisťování a je využívána všude tam, kde by sebeúcta dospělých zaměstnanců mohla bránit v neomezeném ekonomickém rozvoji. Ekonomický přínos dětské práce spočívá jednak ve zvýšení HDP a podtom také v odlehčení nákladů na školství. Je zřejmé, že bez dětské práce by nemohla proběhnout průmyslová revoluce. Za socialismu se dětská práce prováděla ve školách pod názvem Pracovní výchova.</p><p>Dětská práce je většinou vykonávána neplnoletými lidmi a vyznačuje se nehumánními pracovními podmínkami, chybějící ochranou a nízkými mzdami. Zvláště oblíbené oblasti jsou tyto:</p><ul><li>Prostituce</li><li>Hornictví</li><li>Textilní průmysl</li><li>Vojenství</li><li>Žebrota</li><li>Drogový průmysl</li><li>Kapesní krádeže</li><li>Reklama</li><li>Zábavní průmysl</li></ul>" },
    { "title": "Černobyl", "content": "<p>Černobyl (ukrajinsky Чорно́биль, Čornobyl; rusky Черно́быль, Černobyl) je město v Kyjevské oblasti na severu Ukrajiny, poblíž hranic s Běloruskem, v kraji zvaném Polesí. Protéká jím řeka Pripjať. V 70. letech 20. století byla 15 km severozápadně od města postavena Černobylská jaderná elektrárna, v níž došlo roku 1986 závažné havárii, rozsahem následků nejhorší v dějinách jaderné energetiky. Po nehodě bylo okolí elektrárny evakuováno a uzavřeno. Město Černobyl, ve které do té doby žilo asi 14 tisíc obyvatel, zůstalo téměř opuštěné. Roku 2017 zde žilo 690 obyvatel.</p>" },
    { "title": "Most", "content": "<p>Most (německy Brüx, latinsky Pons) je statutární město v severozápadních Čechách (Ústecký kraj). Žije zde přibližně 66 tisíc obyvatel. Historické město bylo v 70. a 80. letech 20. století téměř zcela zbořeno kvůli těžbě uhlí. Nejcennější stavbou a turistickým lákadlem je kostel Nanebevzetí P. Marie, roku 1975 přesunutý na současné místo, a hrad Hněvín na kopci nad městem.</p>" },
    { "title": "Kyklop", "content": "<p>Kyklop je přezdívka dieselelektrických lokomotiv řady 759. Lokomotiva řady 759 (do roku 1987 řada T 499.0) je dieselová lokomotiva s elektrickým přenosem výkonu určená původně pro vozbu rychlíků na hlavních tratích. Pro svůj tvar čela s jedním velkým kulatým reflektorem pod oknem stanoviště strojvedoucího si vysloužila přezdívku „kyklop“. Dva prototypy byly v pražské ČKD vyrobeny v roce 1974 jako plánovaná náhrada nejvýkonnějších parních lokomotiv na neelektrifikovaných tratích. Během následujících let prošly dlouhodobým testováním, mimo jiné i na expresu Ostravan z Bohumína do Prahy. Při zkouškách roku 1976 dosáhl první prototyp rychlosti 176 km/h a drží tak i v současnosti stále platný rychlostní rekord tuzemských motorových lokomotiv. K sériové výrobě však nedošlo a ani oba prototypy se v provozu dlouhodobě neudržely – po ukončení zkoušek přešly jako pronajaté do nákladní dopravy. Po mnoha závadách a požáru byl první prototyp odstaven koncem roku 1979 a krátce nato podobný osud potkal i druhý stroj. Oba stroje zakoupil Výzkumný ústav železniční (VÚŽ) a využíval lokomotivu T 499.0002 na zkušebním okruhu v Cerhenicích jako zátěžové a brzdicí vozidlo. První stroj byl zlikvidován roku 1989 po nárazových zkouškách.</p>" }
  ];
  
  let posts = document.querySelector("#posts") 
  
  let counter = 0; 
  
  displayPage(counter);
  
  function displayPage(startIndex) {
    let endIndex = startIndex + 3;
    for(let i = startIndex; i < endIndex;i++) { 
      let article = document.createElement("div");
      let headline = document.createElement("h1");
      headline.textContent = clanky[i].title;
      let content = document.createElement("div");
      content.innerHTML = clanky[i].content;
      article.append(headline);
      article.append(content);
      posts.append(article);
    }
  }

  document.addEventListener("scroll", () => {
    let { scrollTop, clientHeight, scrollHeight } = document.documentElement;
    if(Math.ceil(scrollTop + clientHeight) >= scrollHeight) { 
      counter = counter + 3;
      displayPage(counter);
    }
  })